spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: "jdbc:postgresql://dbpostgresql:5432/billBD"
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8081